### PR TITLE
fix openbucket with password

### PR DESCRIPTION
**Pull request by jordanclark**

### CODE REVIEW

**Comment by bdw429s** [comment]
@jordanclark This seems to have broken the build.  Can you confirm if the tests are passing locally for you?

**Comment by jordanclark** [comment]
@bdw429s I can confirm that password only authentication works with this fix, it just took me a while to figure out how to run the built in tests, and yes they are passing.

**Comment by bentonam** [comment]
@jordanclark since buckets don't have passwords as of Couchbase 5.0+ and RBAC is used instead it might be better to change this from: 

```
} else if (len(configData.password)) { // else we must be connecting to an older version of Couchbase
      bucket = variables.couchbaseCluster.openBucket(
        javaCast( "string", configData.bucketName )
      );
    }
```
To: 

```
} else if (len(configData.password)) { // else we must be connecting to an older version of Couchbase
      variables.couchbaseCluster.authenticate(
        javaCast( "string", configData.bucketName ),
        javaCast( "string", configData.password )
      );
      bucket = variables.couchbaseCluster.openBucket(
        javaCast( "string", configData.bucketName )
      );
    }
```

As that is what the SDK is doing internally anyway, by using the bucketName as the username.  What version(s) of Couchbase are you using to verify the build against?

**Comment by bdw429s** [comment]
I've reverted this for now until we can hash out the needed changes @jordanclark 
https://github.com/Ortus-Solutions/cfcouchbase-sdk/pull/19

@bentonam Thanks for chiming in :)

**Pull request merged**
