### PR TITLE
Version bump

### PR DESCRIPTION
**Pull request by jordanclark**

### CODE REVIEW

**Comment by bentonam** [comment]
@jordanclark  The latest version of the Java-SDK is 2.7.7, the 2.5.x release of the SDK was end-of-life in March 2019 and is end of support in March of 2020 (https://www.couchbase.com/support-policy)

- https://docs.couchbase.com/java-sdk/2.7/sdk-release-notes.html
- https://docs.couchbase.com/sdk-api/couchbase-java-client-2.7.7/
- https://mvnrepository.com/artifact/com.couchbase.client/java-client/2.7.7

This adds support for Compression, Response Time Observability, and Analytics, amongst other things.  

There are a couple of dependencies that you will want to make sure are updated/add as well 

- com.couchbase.client:java-client:2.7.7
- com.couchbase.client:core-io:1.7.7
- io.reactivex:rxjava:1.3.8
- io.opentracing:opentracing-api:0.31.0

**Comment by lmajano** [comment]
revisiting this pull so ti does not remain open forever.  @bentonam what would you like to do? @jordanclark did you update anything else?

**Comment by bentonam** [comment]
@lmajano  it's mainly about the support policy, the Java SDK 2.5.x was End of Life March 2019, and is End of Support March 2020.  SDK 2.7.x is End of Life April 2020 and End of Support April 2021.  

I figure if it's being updated, might as well update to the latest.  I don't see anything wrong with merging as long as the build succeeds.

**Comment by lmajano** [comment]
Well, the pull request is for 2.5.9?

**Comment by bentonam** [comment]
It was a minor update from 2.5.5 to 2.5.9 I'm guessing because there were some bug fixes that he needed.  It could be merged if the build succeeds.  I was simply stating if someone is going to update the JDK we might as well update to the latest version.

**Comment by lmajano** [comment]
Ahh I get you now!  @jordanclark would you be willing to update to the latest SDK instead?

**Comment by bdw429s** [comment]
This is moot now with the recent rewrite to 3.x

**Pull request closed without merging**
